version: "3.9"
services:
    cifra-api:
        build: ./src
        image: wouterfennis.cifra-api:latest
        ports:
            - "8080:8080"
            - "8443:8443"
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=https://+:8443;http://+:8080
          - ASPNETCORE_Kestrel__Certificates__Default__Password=password
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
          - $USERPROFILE/.aspnet/https:/https:ro