version: "3.9"
services:
    cifra-api:
        build: 
            context: ./src
        image: 192.168.0.184:5000/wouterfennis.cifra.api:linux-arm64
        ports:
            - "8080:8080"
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=http://+:8080;
        volumes:
          - K:/Git/Cifra/data:/data:rw