version: "3.9"
services:
    cifra-api:
        build: ./src
        image: wouterfennis.cifra-api:latest
        ports:
            - "8443:8443"
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=https://+:8443;
          - ASPNETCORE_Kestrel__Certificates__Default__Password=password
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
          - $USERPROFILE/.aspnet/https:/https:ro
        links:
          - "db:database"
    db:
        image: mysql:latest
        ports: 
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_USER=cifra-db-user
          - MYSQL_PASSWORD=password
        volumes:
          - dbdata:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin:latest
        ports: 
          - "8090:80"
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_USER=cifra-db-user
          - MYSQL_PASSWORD=password
volumes:
    dbdata: