version: "3.9"
services:
    cifra-api:
        build: 
            context: ./src
            #args:
                #RUNTIME: win-x64
             #   RUNTIME: linux-arm64
        image: 192.168.0.184:5000/wouterfennis.cifra.api:linux-arm64
        ports:
            - "8443:8443"
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=https://+:8443;
          - ASPNETCORE_Kestrel__Certificates__Default__Password=password
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
          - $USERPROFILE/.aspnet/https:/https:ro
          - C:/Git/Cifra/data:/data:rw