version: "3.9"
services:
    cifra-api:
        build: 
            context: ./src
            dockerfile: Dockerfile.Api
        image: 192.168.0.184:5000/cifra.api:dev
        ports:
            - "8080:8080"
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=http://+:8080;
        volumes:
          - K:/Git/Cifra/data:/data:rw

    cifra-front-end:
        build: 
            context: ./src/Cifra.Frontend
            dockerfile: Dockerfile.Frontend
        image: 192.168.0.184:5000/cifra.frontend:dev
        ports:
            - "8080:8090"
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=http://+:8080;