version: "3.9"
services:
    cifra-api:
        build: 
            context: .
            dockerfile: ./Dockerfile.Api
            args: 
              NUGET_AUTH_USERNAME: ${NUGET_AUTH_USERNAME}
              NUGET_AUTH_TOKEN: ${NUGET_AUTH_PASSWORD}
        image: wouterfennis/cifra-api:dev
        expose:
            - "8090"
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=http://+:8090;
        volumes:
          - K:/Git/Cifra/data:/data:rw

    cifra-front-end:
        build: 
            context: .
            dockerfile: ./Dockerfile.Frontend
            args: 
              NUGET_AUTH_USERNAME: ${NUGET_AUTH_USERNAME}
              NUGET_AUTH_TOKEN: ${NUGET_AUTH_PASSWORD}
        image: wouterfennis/cifra-frontend:dev
        ports:
            - "8080:8080"
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=http://+:8080;
          - CifraApiBaseUrl=http://cifra-api:8090
        links:
            - cifra-api