name: Continuous Deployment Dev release

on:
  pull_request:
    branches:    
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: Azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION }}","tenantId":"${{ secrets.AZURE_TENANT }}"}'

    - uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name cifra-rg --location westeurope
          echo "Azure resource group created"

    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: cifra-rg
        template: ./azure/main.bicep
        failOnStdErr: true

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'cifra-api'
        images: 'wouterfennis/cifra-api:dev'

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'cifra-dev'
        images: 'wouterfennis/cifra-frontend:dev'