name: Continuous Integration Main build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Determine version number
      uses: paulhatch/semantic-version@v5.3.0
      id: versioning
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}"
        bump_each_commit: false
        search_commit_body: false
        # If enabled, diagnostic information will be added to the action output.
        debug: false
        # If true, the branch will be used to select the maximum version.
        version_from_branch: false
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        source-url: https://nuget.pkg.github.com/wouterfennis/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build project
      run: dotnet build --no-restore --configuration Release
    - name: Test project
      run: dotnet test --no-build --configuration Release
    - name: Pack
      run: dotnet pack ./src/Cifra.Api.Client/Cifra.Api.Client.csproj --no-build --configuration Release
    - name: Publish
      run: dotnet nuget push "./src/Cifra.Api.Client/bin/Release/Cifra.Api.Client.*.nupkg" --source https://nuget.pkg.github.com/wouterfennis/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          context: .
          file: ./Dockerfile.Frontend
          push: true
          build-args: |
            NUGET_AUTH_USERNAME=${{secrets.NUGET_USERNAME}}
            NUGET_AUTH_TOKEN=${{secrets.NUGET_TOKEN}}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/cifra-frontend:${{GITHUB.RUN_ID}}
            ${{ secrets.DOCKER_HUB_USERNAME }}/cifra-frontend:1.0
            ${{ secrets.DOCKER_HUB_USERNAME }}/cifra-frontend:latest
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          context: .
          file: ./Dockerfile.Api
          push: true
          build-args: |
            NUGET_AUTH_USERNAME=${{secrets.NUGET_USERNAME}}
            NUGET_AUTH_TOKEN=${{secrets.NUGET_TOKEN}}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/cifra-api:${{GITHUB.RUN_ID}}
            ${{ secrets.DOCKER_HUB_USERNAME }}/cifra-api:1.0
            ${{ secrets.DOCKER_HUB_USERNAME }}/cifra-api:latest