name: Continuous Integration Main build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/wouterfennis/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies of project
      run: dotnet restore
    - name: Build project
      run: dotnet build --no-restore --configuration Release
    - name: Run tests
      run: dotnet test --no-restore
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish project for Linux x64
      run: dotnet publish ./src/Cifra.ConsoleHost/Cifra.ConsoleHost.csproj --configuration Release --no-restore -p:PublishProfile=Linux64
    - name: Upload Linux x64 Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Linux64
        path: |
          ./src/Cifra.ConsoleHost/bin/Release/net5.0/publishLinux64/Cifra
    - name: Publish project for Mac OSX x64
      run: dotnet publish ./src/Cifra.ConsoleHost/Cifra.ConsoleHost.csproj --configuration Release --no-restore -p:PublishProfile=Osx64 -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Upload Osx x64 Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Osx64
        path: |
          ./src/Cifra.ConsoleHost/bin/Release/net5.0/publishOsx64/Cifra
    - name: Publish project for Windows x64
      run: dotnet publish ./src/Cifra.ConsoleHost/Cifra.ConsoleHost.csproj --configuration Release --no-restore -p:PublishProfile=Windows64 -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Upload Windows x64 Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Windows64
        path: |
          ./src/Cifra.ConsoleHost/bin/Release/net5.0/publishWindows64/Cifra.exe