name: Continuous Integration Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        source-url: https://nuget.pkg.github.com/wouterfennis/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build project
      run: dotnet build --no-restore --configuration Release
    - name: Test project
      run: dotnet test
    - name: Pack
      run: dotnet pack ./src/Cifra.Api.Client/Cifra.Api.Client.csproj --no-build --configuration Release --version-suffix ${{GITHUB.RUN_ID}}
    - name: Publish
      run: dotnet nuget push "./src/Cifra.Api.Client/bin/Release/Cifra.Api.Client.*.nupkg" --source https://nuget.pkg.github.com/wouterfennis/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          context: .
          file: ./Dockerfile.Frontend
          push: true
          build-args: |
            NUGET_AUTH_USERNAME=${{secrets.NUGET_USERNAME}}
            NUGET_AUTH_TOKEN=${{secrets.NUGET_TOKEN}}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/cifra-frontend:${{GITHUB.RUN_ID}}
            ${{ secrets.DOCKER_HUB_USERNAME }}/cifra-frontend:dev
            ${{ secrets.DOCKER_HUB_USERNAME }}/cifra-frontend:latest
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          context: .
          file: ./Dockerfile.Api
          push: true
          build-args: |
            NUGET_AUTH_USERNAME=${{secrets.NUGET_USERNAME}}
            NUGET_AUTH_TOKEN=${{secrets.NUGET_TOKEN}}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/cifra-api:${{GITHUB.RUN_ID}}
            ${{ secrets.DOCKER_HUB_USERNAME }}/cifra-api:dev
            ${{ secrets.DOCKER_HUB_USERNAME }}/cifra-api:latest