name: Continuous Integration Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/wouterfennis/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore ./src/Cifra.Api.Client/Cifra.Api.Client.csproj
    - name: Build project
      run: dotnet build ./src/Cifra.Api.Client/Cifra.Api.Client.csproj --no-restore --configuration Release
    - name: Pack
      run: dotnet pack ./src/Cifra.Api.Client/Cifra.Api.Client.csproj --no-build --configuration Release --version-suffix ${{GITHUB_RUN_ID
      - name: Publish
      run: dotnet nuget push "./src/Cifra.Api.Client/bin/Release/Cifra.Api.Client.*.nupkg" --source https://nuget.pkg.github.com/wouterfennis/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate}}
