name: Continuous Integration Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/wouterfennis/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies of project
      run: dotnet restore
    - name: Build project
      run: dotnet build --no-restore --configuration Release
    - name: Run tests
      run: dotnet test --no-restore
